server:
  port: 7070
spring:
  application:
    name: back-server
  profiles:
    active: dev
mybatis-plus:
  #type-handlers-package: org.uppower.qule.core.typehandler
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false
  mapper-locations: classpath*:/mapper/*.xml
  check-config-location: true
