spring:
  redis:
    port: 63779
    host: 47.115.130.89
    password: Sevenlion7
  datasource:
    url: jdbc:mysql://rm-wz9g7s1hz6b7jw0nq3o.mysql.rds.aliyuncs.com:3306/sevenlion_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    username: sevenlion
    password: Sevenlion7
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 100
      max-wait: 60000
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    host: 47.115.130.89
    port: 5672
    username: sevenlion
    password: sevenlion
    virtual-host: /
feign:
  sentinel:
    enabled: true
sevenlion:
  security:
    name: web
    injectClass: org.uppower.sevenlion.common.model.user.UserInfo
    accessTokenExpireIn: 720000
  swagger:
    scanUrl: org.uppower.sevenlion.web.ums.server.controller
    enable: true
    title: 前台ums
    description: ums接口详情
    version: 1.0