spring:
  application:
    name: sevenlion-gateway
server:
  port: 7777
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 展示详情
      show-details: always

